version: '3.1'

services:

  db:
    container_name: meat-mongodb
    image: mongo
    #restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data/db:/data/db
    ports:
      - 2717:27017
  
  api:
    container_name: meat-api
    build: '.'
    volumes:
      - ./dist/:/app
      - ./node_modules:/app/node_modules
    environment: 
      NODE_ENV: development
      DB_URL: mongodb://db/meat-api
    depends_on:
      - db
    links:
      - db
    ports:
      - 3000:3000