version: '3.1'

services:

  db:
    container_name: meat-mongodb
    image: mongo
    #restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - /home/fernando_lopes/workspace/cursos/node/meat-mongodb:/data/db
    ports:
      - 2717:27017
